name: Build and Sign macOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Build & Sign package
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PWD: ${{ secrets.MY_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          export KEYCHAIN=$(pwd)/build.keychain
          security create-keychain -p $KEYCHAIN_PWD $KEYCHAIN
          security default-keychain -s $KEYCHAIN
          security unlock-keychain -p $KEYCHAIN_PWD $KEYCHAIN
          security import certificate.p12 -k $KEYCHAIN -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PWD $KEYCHAIN
          ./gradlew :desktop:notarizeDmg \
               -Pcompose.desktop.mac.sign=true \
               -Pcompose.desktop.mac.signing.identity=${{ secrets.APPLE_SIGN_ID }} \
               -Pcompose.desktop.mac.notarization.appleID=${{ secrets.APPLE_ID }} \
               -Pcompose.desktop.mac.notarization.password=${{ secrets.NOTARIZATION_PWD }} \
               -Pcompose.desktop.mac.signing.keychain=$KEYCHAIN

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ComposeWidgetsGallery-1.0.0.dmg
          path: desktop/build/compose/binaries/main/dmg/ComposeWidgetsGallery-1.0.0.dmg
