name: Build and Sign macOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Build & Sign package
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MY_PWD: ${{ secrets.MY_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $MY_PWD build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p $MY_PWD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MY_PWD build.keychain
          ./gradlew :desktop:packageDmg \
               -Pcompose.desktop.mac.sign=true \
               -Pcompose.desktop.mac.signing.identity="Alexey Tsvetkov" \
               -Pcompose.desktop.mac.signing.keychain=build.keychain

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ComposeWidgetsGallery-1.0.0.dmg
          path: desktop/build/compose/binaries/main/dmg/ComposeWidgetsGallery-1.0.0.dmg
